apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-pocduction-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: java-app
        image: 861276087074.dkr.ecr.ap-south-1.amazonaws.com/finacplus/javaapp:latest
        ports:
        - containerPort: 8085